// This file is automatically generated by compileInstructionsTable.m
typedef enum instructionType_e {
    I_set=1,
    I_load=2,
    I_sum=3,
    I_sumprod=4,
    I_inv=5,
    I_minus_inv_sqr=6,
    I_2_inv_cube=7,
    I_div=8,
    I_minus_dot=9,
    I_minus_dot_div=10,
    I_plus_minus_dot=11,
    I_plus_sqr=12,
    I_plus_abs=13,
    I_plus_minus_dot_div=14,
    I_min=15,
    I_min0=16,
    I_max=17,
    I_max0=18,
    I_max_abs=19,
    I_clp=20,
    I_exp=21,
    I_log=22,
    I_cos=23,
    I_minus_cos=24,
    I_sin=25,
    I_minus_sin=26,
    I_abs=27,
    I_sign=28,
    I_sqrt=29,
    I_Dsqrt=30,
    I_DDsqrt=31,
    I_sqr=32,
    I_2times=33,
    I_2=34,
    I_cube=35,
    I_3sqr=36,
    I_6times=37,
    I_atan=38,
    I_Datan=39,
    I_DDatan=40,
    I_luS2A=41,
    I_luS2Asym=42,
    I_mldivideA2F1=43,
    I_mldivideA2Fn=44,
    I_Mnorm2=45,
    I_Mnorm1=46,
    I_Mnorminf=47,
    I_Mplus=48,
    I_Mmtimes=49,
    I_Mtimes=50,
    I_Msum=51,
    I_Mmin=52,
    I_Mones=53,
    I_Mzeros=54,
    I_Meye=55,
    I_Mdiag=56,
    I_Mclp=57,
    I_Mctranspose=58,
    I_Msubsref=59,
    I_Mtprod=60,
    I_Mtprod_matlab=61,
    I_Mfull=62,
    I_Mreshape=63,
    I_Mrepmat=64,
    I_Mcat=65,
    I_Mlu=66,
    I_Mldl=67,
    I_Mchol=68,
    I_Mmldivide_l1=69,
    I_Mmldivide_u=70,
    I_Mmldivide_u1=71,
    I_Mmldivide_d=72,
    I_Mrdivide=73,
    I_Mcompose=74,
} instructionType_t;
// profile defines
#define P_nsum 1
#define P_nprod 2
#define P_ndiv 3
#define P_nif 4
#define P_nclp 5
#define P_nabs 6
#define P_nsign 7
#define P_nsqrt 8
#define P_npow 9
#define P_ntrig 10
#define P_nlog 11
#define P_nexp 12
#define P_numfpack 13
#define P_nCountFlops 13
