// This file is automatically generated by compileInstructionsTable.m
typedef enum instructionType_e {
    I_set=1,
    I_load=2,
    I_sum=3,
    I_sumprod=4,
    I_inv=5,
    I_minus_inv_sqr=6,
    I_2_inv_cube=7,
    I_div=8,
    I_minus_dot=9,
    I_minus_dot_div=10,
    I_plus_minus_dot=11,
    I_plus_sqr=12,
    I_plus_abs=13,
    I_plus_minus_dot_div=14,
    I_min=15,
    I_min0=16,
    I_max=17,
    I_max0=18,
    I_max_abs=19,
    I_clp=20,
    I_exp=21,
    I_log=22,
    I_cos=23,
    I_minus_cos=24,
    I_sin=25,
    I_minus_sin=26,
    I_round=27,
    I_ceil=28,
    I_floor=29,
    I_abs=30,
    I_sign=31,
    I_sqrt=32,
    I_Dsqrt=33,
    I_DDsqrt=34,
    I_sqr=35,
    I_2times=36,
    I_2=37,
    I_cube=38,
    I_3sqr=39,
    I_6times=40,
    I_atan=41,
    I_Datan=42,
    I_DDatan=43,
    I_luS2A=44,
    I_luS2Asym=45,
    I_mldivideA2F1=46,
    I_mldivideA2Fn=47,
    I_Mnorm2=48,
    I_Mnorm1=49,
    I_Mnorminf=50,
    I_Mplus=51,
    I_Mmtimes=52,
    I_Mtimes=53,
    I_Msum=54,
    I_Mmin=55,
    I_Mones=56,
    I_Mzeros=57,
    I_Meye=58,
    I_Mdiag=59,
    I_Mclp=60,
    I_Mctranspose=61,
    I_Msubsref=62,
    I_Mtprod=63,
    I_Mtprod_matlab=64,
    I_Mfull=65,
    I_Mreshape=66,
    I_Mrepmat=67,
    I_Mcat=68,
    I_Mlu=69,
    I_Mldl=70,
    I_Mchol=71,
    I_Mmldivide_l1=72,
    I_Mmldivide_u=73,
    I_Mmldivide_u1=74,
    I_Mmldivide_d=75,
    I_Mrdivide=76,
    I_Mcompose=77,
} instructionType_t;
// profile defines
#define P_nsum 1
#define P_nprod 2
#define P_ndiv 3
#define P_nif 4
#define P_nclp 5
#define P_nabs 6
#define P_nround 7
#define P_nceil 8
#define P_nfloor 9
#define P_nsign 10
#define P_nsqrt 11
#define P_npow 12
#define P_ntrig 13
#define P_nlog 14
#define P_nexp 15
#define P_numfpack 16
#define P_nCountFlops 16
